In [2]:
from google.colab import files
uploaded = files.upload()

Saving Crime.csv to Crime (1).csv

In [ ]:
uploaded = files.upload()

Saving Crime Person.csv to Crime Person.csv

In [ ]:
uploaded = files.upload()

Saving People.csv to People.csv

In [ ]:
uploaded = files.upload()

Saving Crime Roles.csv to Crime Roles.csv

In [ ]:
uploaded = files.upload()

Saving Crime Type.csv to Crime Type.csv

In [3]:
import pandas as pd

In [4]:

crime = pd.read_csv("/content/Crime.csv")
crime_person = pd.read_csv("/content/Crime Person.csv")
people = pd.read_csv("/content/People.csv")
crime_types = pd.read_csv("/content/Crime Type.csv")
crime_roles = pd.read_csv("/content/Crime Roles.csv")

In [5]:
crime.head()

,Crime ID,Crime Date,Latitude,Longitude,Crime Type ID,Resolved,People Involved,Crime DateTime
0,1,01-09-2021,51.464348,-0.140717,1,0,2,01.09.2021 02:00
1,2,02-08-2023,51.498368,-0.059213,9,0,2,02.08.2023 17:30
2,3,10-04-2022,51.533161,-0.055350,12,0,2,10.04.2022 22:35
3,4,21-09-2023,51.447567,-0.092034,11,1,5,21.09.2023 01:45
4,5,02-04-2022,51.498684,-0.181090,12,1,2,02.04.2022 20:40

In [6]:
crime_person.head()

   Crime ID  People Involved  Crime Role ID  Person ID
0         1                2              1        782
1         1                2              5       3930
2         2                2              1         25
3         2                2              5       1036
4         3                2              1       2751

In [ ]:
people.head()

   Person ID             Name Date of Birth Gender   Ethnicity
0          1  Clarence Bowers    02-10-1988   Male  Ethnicity3
1          2     Timothy Pugh    21-12-1993   Male  Ethnicity3
2          3      Kaleb Nixon    28-09-1974   Male  Ethnicity5
3          4     Ronnie Curry    03-01-1973   Male  Ethnicity1
4          5       Drew Stein    24-11-1996   Male  Ethnicity1

In [ ]:
crime_types.head()

   Crime Type ID                         Crime
0              1         Anti-Social Behaviour
1              2                 Bicycle Theft
2              3                      Burglary
3              4     Criminal Damage and Arson
4              5  Drugs and Illegal Substances

In [ ]:
crime_roles.head()

   Crime Role ID        Role
0              1      Victim
1              2     Witness
2              3  Accomplice
3              4   Informant
4              5    Offender

In [ ]:
crime.isnull().sum()

Crime ID           0
Crime Date         0
Latitude           0
Longitude          0
Crime Type ID      0
Resolved           0
People Involved    0
Crime DateTime     0
dtype: int64

In [ ]:
crime_person.isnull().sum()

Crime ID           0
People Involved    0
Crime Role ID      0
Person ID          0
dtype: int64

In [ ]:
people.isnull().sum()

Person ID        0
Name             0
Date of Birth    0
Gender           0
Ethnicity        0
dtype: int64

In [ ]:
crime_types.isnull().sum()

Crime Type ID    0
Crime            0
dtype: int64

In [ ]:
crime_roles.isnull().sum()

Crime Role ID    0
Role             0
dtype: int64

In [ ]:
crime.duplicated().sum()

np.int64(0)

In [ ]:
crime_person.duplicated().sum()

np.int64(0)

In [ ]:
crime_roles.duplicated().sum()

np.int64(0)

In [ ]:
crime_types.duplicated().sum()

np.int64(0)

In [ ]:
people.duplicated().sum()

np.int64(0)

In [ ]:

crime["Crime Date"] = pd.to_datetime(crime["Crime Date"], errors="coerce")

crime["Latitude"] = pd.to_numeric(crime["Latitude"], errors="coerce")
crime["Longitude"] = pd.to_numeric(crime["Longitude"], errors="coerce")

In [ ]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Crime ID         2500 non-null   int64
 1   Crime Date       1026 non-null   datetime64[ns]
 2   Latitude         2500 non-null   float64
 3   Longitude        2500 non-null   float64
 4   Crime Type ID    2500 non-null   int64
 5   Resolved         2500 non-null   int64
 6   People Involved  2500 non-null   int64
 7   Crime DateTime   2500 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(4), object(1)
memory usage: 156.4+ KB

In [ ]:
crime["Crime Date"]

0      2021-01-09
1      2023-02-08
2      2022-10-04
3             NaT
4      2022-02-04
          ...
2495   2021-04-10
2496   2022-12-01
2497   2022-12-10
2498   2023-10-09
2499   2021-03-10
Name: Crime Date, Length: 2500, dtype: datetime64[ns]

In [8]:
crime["Crime Date"].head(10)

0    01-09-2021
1    02-08-2023
2    10-04-2022
3    21-09-2023
4    02-04-2022
5    19-09-2022
6    15-09-2023
7    21-07-2023
8    11-09-2022
9    19-10-2023
Name: Crime Date, dtype: object

In [10]:
crime["Crime Date"] = pd.to_datetime(crime["Crime Date"], format="%d-%m-%Y", errors="coerce")

In [13]:
crime["Crime Date"].head(10)

0   2021-09-01
1   2023-08-02
2   2022-04-10
3   2023-09-21
4   2022-04-02
5   2022-09-19
6   2023-09-15
7   2023-07-21
8   2022-09-11
9   2023-10-19
Name: Crime Date, dtype: datetime64[ns]

In [14]:
crime["Crime Date"].isnull().sum()

np.int64(0)

In [15]:
crime["Crime Date"]

0      2021-09-01
1      2023-08-02
2      2022-04-10
3      2023-09-21
4      2022-04-02
          ...
2495   2021-10-04
2496   2022-01-12
2497   2022-10-12
2498   2023-09-10
2499   2021-10-03
Name: Crime Date, Length: 2500, dtype: datetime64[ns]